// <auto-generated />
using System;
using Lab1ASP.NetCore.BerrasData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab1ASP.NetCore.Migrations
{
    [DbContext(typeof(BerrasDBContext))]
    partial class BerrasDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab1ASP.NetCore.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Productionyear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatsLeft")
                        .HasColumnType("int");

                    b.Property<string>("Showtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Genre = "Action",
                            Productionyear = "2017",
                            SeatsLeft = 50,
                            Showtime = "Juni 14-2020 17:30 PM",
                            Title = "Black Panther"
                        },
                        new
                        {
                            ID = 2,
                            Genre = "Action",
                            Productionyear = "2017",
                            SeatsLeft = 50,
                            Showtime = "Juni 14-2020 15:00 PM",
                            Title = "Wonder Woman"
                        },
                        new
                        {
                            ID = 3,
                            Genre = "Action",
                            Productionyear = "2019",
                            SeatsLeft = 50,
                            Showtime = "Juni 16-2020 17:00 PM",
                            Title = "Avengers:Endgame "
                        },
                        new
                        {
                            ID = 4,
                            Genre = "Drama",
                            Productionyear = "2019",
                            SeatsLeft = 50,
                            Showtime = "Juni 16-2020 20:00 PM",
                            Title = "The Irishman"
                        },
                        new
                        {
                            ID = 5,
                            Genre = "Drama",
                            Productionyear = "2018",
                            SeatsLeft = 50,
                            Showtime = "Juni 17-2020 15:00 PM",
                            Title = "Lady Bird"
                        });
                });

            modelBuilder.Entity("Lab1ASP.NetCore.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmmountTickets")
                        .HasColumnType("int");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<string>("MovieTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("MovieID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Lab1ASP.NetCore.Models.Order", b =>
                {
                    b.HasOne("Lab1ASP.NetCore.Models.Movie", "Movie")
                        .WithMany("Orders")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
